title: Bug Hotel
hero_image: images/banner.png
description: Fix a strange hotel one room at a time by debugging HTML, CSS, and JavaScript.
listed: false
pdf: false
steps:
  - title: 1
  - title: 2
    completion:
      - engaged
  - title: 3
  - title: 4
  - title: 5
  - title: 6
    completion:
      - internal
  - title: 7
    challenge: true
    completion:
      - external
